// <auto-generated />
using System;
using API.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(MahasiswaContext))]
    [Migration("20230516022722_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Db.mahasiswa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("alamat")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alamat");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nama");

                    b.Property<int>("umur")
                        .HasColumnType("integer")
                        .HasColumnName("umur");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("id");

                    b.ToTable("mahasiswa");

                    b.HasData(
                        new
                        {
                            id = 1,
                            alamat = "Dago - Bandung",
                            created_date = new DateTime(2023, 5, 16, 2, 27, 22, 572, DateTimeKind.Utc).AddTicks(8742),
                            is_active = true,
                            nama = "Arya Santoso",
                            umur = 20,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            alamat = "Nginden - Surabaya",
                            created_date = new DateTime(2023, 5, 16, 2, 27, 22, 572, DateTimeKind.Utc).AddTicks(8750),
                            is_active = true,
                            nama = "Astrid Ardia",
                            umur = 21,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 3,
                            alamat = "Cicaheum - Bandung",
                            created_date = new DateTime(2023, 5, 16, 2, 27, 22, 572, DateTimeKind.Utc).AddTicks(8752),
                            is_active = true,
                            nama = "Budi Arga",
                            umur = 22,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 4,
                            alamat = "Menteng - Jakarta",
                            created_date = new DateTime(2023, 5, 16, 2, 27, 22, 572, DateTimeKind.Utc).AddTicks(8754),
                            is_active = true,
                            nama = "Dini Andari",
                            umur = 21,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 5,
                            alamat = "Merdeka - Malang",
                            created_date = new DateTime(2023, 5, 16, 2, 27, 22, 572, DateTimeKind.Utc).AddTicks(8757),
                            is_active = true,
                            nama = "Dwi Ciska",
                            umur = 22,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 6,
                            alamat = "Dago - Bandung",
                            created_date = new DateTime(2023, 5, 16, 2, 27, 22, 572, DateTimeKind.Utc).AddTicks(8759),
                            is_active = true,
                            nama = "Edi Prastowo",
                            umur = 23,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 7,
                            alamat = "Setiabudi - Bandung",
                            created_date = new DateTime(2023, 5, 16, 2, 27, 22, 572, DateTimeKind.Utc).AddTicks(8761),
                            is_active = true,
                            nama = "Eka Sapta",
                            umur = 22,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 8,
                            alamat = "Mande - Mataram",
                            created_date = new DateTime(2023, 5, 16, 2, 27, 22, 572, DateTimeKind.Utc).AddTicks(8763),
                            is_active = true,
                            nama = "Fifin Aliana ",
                            umur = 24,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 9,
                            alamat = "Perak - Surabaya",
                            created_date = new DateTime(2023, 5, 16, 2, 27, 22, 572, DateTimeKind.Utc).AddTicks(8765),
                            is_active = true,
                            nama = "Giri Rekso",
                            umur = 21,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 10,
                            alamat = "Antapani - Bandung",
                            created_date = new DateTime(2023, 5, 16, 2, 27, 22, 572, DateTimeKind.Utc).AddTicks(8767),
                            is_active = true,
                            nama = "Heri Ahmad Surya",
                            umur = 24,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
